### ISSUE TITLE
how to fix this error: "AttributeError: 'QuestionGenerator' object has no attribute 'input_file'"?

### ISSUE THREAD

**Issue by r-baradaran** [sumehta/question-generation#1]
I execute this code step by step but i received an error when run:
python question_generator.py -s 'Handheld devices find ways to bolster U.S. homeland defense and response'
Traceback (most recent call last):
  File "question_generator.py", line 51, in <module>
    q = QuestionGenerator()
  File "question_generator.py", line 25, in __init__
    if self.input_file:
AttributeError: 'QuestionGenerator' object has no attribute 'input_file'
please help me how to fit it?
thanks in advance.

**Comment by sumehta** [comment]
Fixed the issue.
