### ISSUE TITLE
how to execute this code on file?

### ISSUE THREAD

**Issue by r-baradaran** [sumehta/question-generation#2]
Hello,
i want to create question for a file with several paragraph.
how do this?
also when i run this code for a paragraph using following command:
**python question.py -s 'Handheld devices find ways to bolster U.S. homeland defense and response'**
nothing printed in output:
**$ python question_generator.py -s 'Handheld devices find ways to bolster U.S. homeland defense and response'**
**$**
It is worth mentioning the "runStanfordParserServer.sh" and "runSSTServer.sh" are running in seperate terminals.
please help me to resolve it.
thank you very much.

**Comment by WangJiexin** [comment]
Hello, I also have the issue that nothing printed in output.
And have you already solved the problem?

**Comment by sumehta** [comment]
@WangJiexin Should work now.

**Comment by sumehta** [comment]
@saeid6366 If you want to run this for paragraphs you need to break down your paragraph into sentences using `nltk.sent_tokenize` or `spacy` and then run it for each sentence using this.

**Comment by ashwarhussain** [comment]
Hello Sneha,
its printing an empty text even for me. I have take code today so its definetly latest. The command that I execute from my Anaconda prompt is given below.

C:\Code\Machine Learning\MyWizard\KLEWER\Question Generation\question-generation-master\question-generation-master\QuestionGeneration\QuestionGeneration>python ..\..\question.py -s "Handheld devices find ways to bolster U.S. homeland defense and response" -t "All"
