### ISSUE TITLE
Given a question and an answer generate a sentence

### ISSUE THREAD

**Issue by jayurbain** [sumehta/question-generation#3]
Nice work.

I think it would be interesting to see the following for this type of problem: given a question and an answer, generate a sentence.

Would be very useful question/answering systems.

Tx,
Jay

**Comment by sumehta** [comment]
@jayurbain: That sounds like an interesting problem to solve, I wonder what would be its application in Q/A systems though. Any thoughts?

**Comment by jayurbain** [comment]
Generating targeted summaries via Q/A.

**Comment by sumehta** [comment]
I see, are there any public datasets for this task that you're aware of?

**Comment by jayurbain** [comment]
> I see, are there any public datasets for this task that you're aware of?

Not that I know of. I'm interested in generated bulleted-like summaries. Sorry for the late reply.

**Comment by sumehta** [comment]
No problem, will get back to you when I have an update.
