### ISSUE TITLE
Taking too long to start servers

### ISSUE THREAD

**Issue by mady143** [sumehta/question-generation#8]
Hi @sumehta ,
I am trying to execute your code that i am trying to run the servers separately in two terminals but its taking  to long to start the servers and seem to be like this for 
**bash runStanfordParserServer.sh**
maxlength = 40
port = 5556
Loading parser from serialized file config/englishFactored.ser.gz ... done [6.2 sec].
Waiting for Connection on Port: 5556
and 
**bash runSSTServer.sh**
Waiting for Connection on Port: 5557
can you please help me to resolve the issue

Thanks and Regards,
Manikantha Sekhar.
Happy Codding....

**Comment by kamalkarki** [comment]
@mady143 @sumehta having same issues.
When I am typing this command - python question.py -s 'Handheld devices find ways to bolster U.S. homeland defense and response'
output is - []

**Comment by mady143** [comment]
@kamalkarki ,
When I am typing this command - python question.py -s 'Handheld devices find ways to bolster U.S. homeland defense and response'
i got the response/Output as
**[{'Q': 'What find ways to bolster U. S. homeland defense and response?', 'A': 'Handheld devices find ways to bolster U. S. homeland defense and response'}, {'Q': 'What do handheld devices find?', 'A': 'Handheld devices find ways to bolster U. S. homeland defense and response'}]**
but i dont know how its works 
if you can know can you please help me with code description and explanation

Thanks and Regards,
Manikantha Sekhar.

Happy Codding...

**Comment by sumehta** [comment]
@kamalkarki Hope you were able to get a non-empty output?

**Comment by mady143** [comment]
@kamalkarki yeah i am getting an empty list as an output how can i resolve this issue,can you tell me 

Thanks and Regards,
Manikantha Sekhar.

Happy Codding..

**Comment by kamalkarki** [comment]
@sumehta I was getting error - unrecognized arguments. Now I have moved to Linux environment and its working fine in it.

**Comment by kamalkarki** [comment]
@mady143 I just ran the mentioned scripts and given commands provided by @sumehta and for time being it is working fine.

**Comment by mady143** [comment]
@kamalkarki @sumehta Thank you Now i was able to run the Script but i can't run these two commands taking to long to start the servers 
**bash runStanfordParserServer.sh
bash runSSTServer.sh** 

Thanks & Regards,
Manikantha Sekhar.

Happy Codding....

**Comment by sumehta** [comment]
Are you sure, it's taking too long? Servers won't output anything unless you run the question.py script.

**Comment by sumehta** [comment]
Hope the issue was resolved.
